google_analytics: UA-155996867-1

header_pages:
  - index.md
  - docs.md
  - about.md

github_corner_url: https://github.com/tofuengine/tofu
github_corner_caption: View source on GitHub

footer: 'follow us on <a href="https://twitter.com/MarcoLizza">twitter</a>'

style: dark
listen_for_clients_preferred_style: false

plugins:
  - jekyll-seo-tag
