# Site settings
title: "#tofuengine"
logo_url: "/assets/images/logo.png"
email: marco.lizza@gmail.com
description: ~ a 2D game engine w/ an eco-friendly pixel-art retro-soul ~
url: "" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

author: # Author details
  name: Marco Lizza
  email: marco.lizza@gmail.com
  url: https://about.me/marco.lizza
  copyright: "&copy; Copyright 2019-2021 by Marco Lizza"

defaults:
  author: marco.lizza

# Profile links, leave blank to ignore
social: 
  github: tofuengine
  twitter: tofuengine
  itchio: tofuengine 
  disqus: tofuengine

# Google Analytics key, leave blank to ignore
google:
  analytics_id: UA-131188350-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/

include:
  - _pages

exclude:
  - CNAME
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache
