style: dark
listen_for_clients_preferred_style: false

google_analytics: UA-155996867-1

github_corner_url: https://github.com/tofuengine/tofu
github_corner_caption: View source on GitHub

header_pages:
  - index.md
  - about.md
  - docs.md
  - roadmap.md

footer: 'join us on <a href="https://discord.gg/CtpBfn">discord</a>'

collections:
  docs:
    output: true

plugins:
  - jekyll-seo-tag
