# Site settings
title: "#tofuengine"
logo_url: "/assets/images/logo.png"
email: marco.lizza@gmail.com
description: ~ a 2D game engine w/ an eco-friendly pixel-art soul ~
url: "" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

author: # Author details
  name: Marco Lizza
  email: marco.lizza@gmail.com
  url: https://about.me/marco.lizza
  copyright: "&copy; Copyright 2019-2021 by Marco Lizza"

# Profile links, leave blank to ignore
social: 
  github: MarcoLizza
  twitter: MarcoLizza
  facebook: marco.lizza
  itchio: MarcoLizza 
  linkedin: marco-lizza-46569a34
  disqus: mode13h-io

# Google Analytics key, leave blank to ignore
google:
  analytics_id: UA-131188350-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/

include:
  - _pages

exclude:
  - CNAME
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache

sass:
  sass_dir: assets/css/_sass
  style: :compressed

plugins_dir:
  - jekyll-tidy

jekyll_tidy:
  compress_html: false
